<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="6" passed="0" failed="3" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-12T22:17:58 IST" name="All Test Suite" finished-at="2024-04-12T22:18:43 IST" duration-ms="45367">
    <groups>
      <group name="Purchase">
        <method signature="Submit_Order.Order(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:rahulsettyacademy.submitorder.Submit_Order@2e385cce]" name="Order" class="rahulsettyacademy.submitorder.Submit_Order"/>
      </group> <!-- Purchase -->
      <group name="errors">
        <method signature="Error_Handling.Login_Error()[pri:0, instance:rahulsettyacademy.submitorder.Error_Handling@2ea41516]" name="Login_Error" class="rahulsettyacademy.submitorder.Error_Handling"/>
      </group> <!-- errors -->
    </groups>
    <test started-at="2024-04-12T22:17:58 IST" name="Error_methods" finished-at="2024-04-12T22:18:15 IST" duration-ms="17372">
      <class name="rahulsettyacademy.submitorder.Error_Handling">
        <test-method is-config="true" signature="browserlunch()[pri:0, instance:rahulsettyacademy.submitorder.Error_Handling@2ea41516]" started-at="2024-04-12T22:17:58 IST" name="browserlunch" finished-at="2024-04-12T22:18:05 IST" duration-ms="7312" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserlunch -->
        <test-method retried="true" signature="Login_Error()[pri:0, instance:rahulsettyacademy.submitorder.Error_Handling@2ea41516]" started-at="2024-04-12T22:18:05 IST" name="Login_Error" finished-at="2024-04-12T22:18:06 IST" duration-ms="806" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorre mail or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorre mail or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at rahulsettyacademy.submitorder.Error_Handling.Login_Error(Error_Handling.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_Error -->
        <test-method is-config="true" signature="close_browser()[pri:0, instance:rahulsettyacademy.submitorder.Error_Handling@2ea41516]" started-at="2024-04-12T22:18:06 IST" name="close_browser" finished-at="2024-04-12T22:18:09 IST" duration-ms="2710" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close_browser -->
        <test-method is-config="true" signature="browserlunch()[pri:0, instance:rahulsettyacademy.submitorder.Error_Handling@2ea41516]" started-at="2024-04-12T22:18:09 IST" name="browserlunch" finished-at="2024-04-12T22:18:11 IST" duration-ms="1645" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserlunch -->
        <test-method signature="Login_Error()[pri:0, instance:rahulsettyacademy.submitorder.Error_Handling@2ea41516]" started-at="2024-04-12T22:18:11 IST" name="Login_Error" finished-at="2024-04-12T22:18:12 IST" duration-ms="1955" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorre mail or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorre mail or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at rahulsettyacademy.submitorder.Error_Handling.Login_Error(Error_Handling.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_Error -->
        <test-method is-config="true" signature="close_browser()[pri:0, instance:rahulsettyacademy.submitorder.Error_Handling@2ea41516]" started-at="2024-04-12T22:18:13 IST" name="close_browser" finished-at="2024-04-12T22:18:15 IST" duration-ms="2293" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close_browser -->
      </class> <!-- rahulsettyacademy.submitorder.Error_Handling -->
    </test> <!-- Error_methods -->
    <test started-at="2024-04-12T22:17:58 IST" name="Submit" finished-at="2024-04-12T22:18:43 IST" duration-ms="45367">
      <class name="rahulsettyacademy.submitorder.Submit_Order">
        <test-method is-config="true" signature="browserlunch()[pri:0, instance:rahulsettyacademy.submitorder.Submit_Order@2e385cce]" started-at="2024-04-12T22:17:58 IST" name="browserlunch" finished-at="2024-04-12T22:18:02 IST" duration-ms="3712" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserlunch -->
        <test-method signature="Order(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:rahulsettyacademy.submitorder.Submit_Order@2e385cce]" started-at="2024-04-12T22:18:02 IST" name="Order" data-provider="getdata" finished-at="2024-04-12T22:18:22 IST" duration-ms="19936" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[sivalakshmidevi9@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Amma@123udemy]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ADIDAS ORIGINAL]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at rahulsettyacademy.submitorder.Submit_Order.Order(Submit_Order.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Order -->
        <test-method is-config="true" signature="close_browser()[pri:0, instance:rahulsettyacademy.submitorder.Submit_Order@2e385cce]" started-at="2024-04-12T22:18:22 IST" name="close_browser" finished-at="2024-04-12T22:18:24 IST" duration-ms="2137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close_browser -->
        <test-method is-config="true" signature="browserlunch()[pri:0, instance:rahulsettyacademy.submitorder.Submit_Order@2e385cce]" started-at="2024-04-12T22:18:24 IST" name="browserlunch" finished-at="2024-04-12T22:18:26 IST" duration-ms="1721" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserlunch -->
        <test-method signature="Order(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:rahulsettyacademy.submitorder.Submit_Order@2e385cce]" started-at="2024-04-12T22:18:26 IST" name="Order" data-provider="getdata" finished-at="2024-04-12T22:18:41 IST" duration-ms="14997" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[shetty@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Iamking@000]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[IPHONE 13 PRO]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at rahulsettyacademy.submitorder.Submit_Order.Order(Submit_Order.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Order -->
        <test-method is-config="true" signature="close_browser()[pri:0, instance:rahulsettyacademy.submitorder.Submit_Order@2e385cce]" started-at="2024-04-12T22:18:41 IST" name="close_browser" finished-at="2024-04-12T22:18:43 IST" duration-ms="2207" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close_browser -->
        <test-method signature="MyOrde()[pri:0, instance:rahulsettyacademy.submitorder.Submit_Order@2e385cce]" started-at="2024-04-12T22:18:43 IST" name="MyOrde" finished-at="2024-04-12T22:18:43 IST" depends-on-methods="rahulsettyacademy.submitorder.Submit_Order.Order" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method rahulsettyacademy.submitorder.Submit_Order.MyOrde() on instance rahulsettyacademy.submitorder.Submit_Order@2e385cce depends on not successfully finished methods 
[rahulsettyacademy.submitorder.Submit_Order.Order() on instance rahulsettyacademy.submitorder.Submit_Order@2e385cce]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method rahulsettyacademy.submitorder.Submit_Order.MyOrde() on instance rahulsettyacademy.submitorder.Submit_Order@2e385cce depends on not successfully finished methods 
[rahulsettyacademy.submitorder.Submit_Order.Order() on instance rahulsettyacademy.submitorder.Submit_Order@2e385cce]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MyOrde -->
      </class> <!-- rahulsettyacademy.submitorder.Submit_Order -->
    </test> <!-- Submit -->
  </suite> <!-- All Test Suite -->
</testng-results>
